"""change messages col to content in intractio message

Revision ID: 4cc9027dcc0d
Revises: 522941979a48
Create Date: 2023-11-12 18:55:40.127207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cc9027dcc0d'
down_revision: Union[str, None] = '522941979a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intercation_messages', sa.Column('content', sa.String(), nullable=True))
    op.add_column('intercation_messages', sa.Column('role', sa.Enum('SYSTEM', 'HUMAN', 'AI', name='intractionroleenum'), nullable=True))
    op.drop_column('intercation_messages', 'message')
    op.drop_column('intercation_messages', 'Role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intercation_messages', sa.Column('Role', postgresql.ENUM('SYSTEM', 'HUMAN', 'AI', name='intractionroleenum'), autoincrement=False, nullable=True))
    op.add_column('intercation_messages', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('intercation_messages', 'role')
    op.drop_column('intercation_messages', 'content')
    # ### end Alembic commands ###
