"""add interaction messages

Revision ID: 522941979a48
Revises: 89d0de5bdda5
Create Date: 2023-11-12 15:38:34.888024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522941979a48'
down_revision: Union[str, None] = '89d0de5bdda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intercation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intraction_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('Role', sa.Enum('SYSTEM', 'HUMAN', 'AI', name='intractionroleenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intraction_id'], ['intractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intercation_messages_id'), 'intercation_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intercation_messages_id'), table_name='intercation_messages')
    op.drop_table('intercation_messages')
    # ### end Alembic commands ###
