"""add name column to intrations

Revision ID: 89d0de5bdda5
Revises: 930e3aa2ee01
Create Date: 2023-11-12 14:44:20.314798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d0de5bdda5'
down_revision: Union[str, None] = '930e3aa2ee01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intractions', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intractions', 'name')
    # ### end Alembic commands ###
